#!/bin/bash

# Ask for versions
read -p "Ruby Version: " RUBY
read -p "Rails Version: " RAILS

# Install requirements
sudo apt-get update
sudo apt-get install -y curl

# Set up rvm
\curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
bash
exit
rvm requirements

# Install ruby
rvm install $RUBY
rvm use $RUBY --default

# Install RubyGems
rvm rubygems current

# Install necessary gems
gem install bundler
gem install rails --version $RAILS

# Exit out of the script
exit
